import type { ForumDataset } from "./domain";

const july = "2026-07-31T08:00:00.000Z";
const august = "2026-08-18T14:20:00.000Z";
const september = "2026-09-08T10:30:00.000Z";

export const forumSeed: ForumDataset = {
  users: [
    {
      id: "atlas",
      username: "atlas",
      displayName: "Atlas",
      accountType: "child",
      guardianUserId: "morgan",
      bio: "Boats, games, animals and machines.",
      nodeId: "forum-plett",
      createdAt: july,
    },
    {
      id: "morgan",
      username: "morgan",
      displayName: "Morgan",
      accountType: "adult",
      bio: "Founder and steward of Forum Plett.",
      nodeId: "forum-plett",
      createdAt: july,
    },
    {
      id: "ines",
      username: "ines",
      displayName: "Inês",
      accountType: "adult",
      bio: "Field observer and mechanical builder.",
      nodeId: "forum-plett",
      createdAt: august,
    },
  ],
  nodes: [
    {
      id: "forum-plett",
      slug: "plett",
      name: "Forum Plett",
      description:
        "A fieldhouse between sea, garden and workshop. Work begins with things that can be handled, observed and changed.",
      locationLabel: "Plettenberg Bay, South Africa",
      visibility: "network",
      createdAt: july,
    },
  ],
  builds: [
    {
      kind: "build",
      id: "build-thetis",
      slug: "thetis",
      title: "Thetis",
      description:
        "An inflatable boat becoming a small sailing and measurement platform.",
      creatorId: "atlas",
      contributorIds: ["atlas", "morgan"],
      nodeId: "forum-plett",
      visibility: "node",
      state: "testing",
      curationStatus: "selected",
      createdAt: july,
      updatedAt: september,
    },
    {
      kind: "build",
      id: "build-deep-sea",
      slug: "deep-sea",
      title: "Deep Sea",
      description:
        "A playable underwater world about pursuit, schooling and the space between creatures.",
      creatorId: "atlas",
      contributorIds: ["atlas"],
      nodeId: "forum-plett",
      visibility: "private",
      state: "building",
      curationStatus: "none",
      createdAt: august,
      updatedAt: september,
    },
    {
      kind: "build",
      id: "build-garden-rover",
      slug: "garden-rover",
      title: "Garden Rover",
      description:
        "A small rover learning to move through garden paths without touching the beds.",
      creatorId: "ines",
      contributorIds: ["ines", "atlas"],
      nodeId: "forum-plett",
      visibility: "network",
      state: "working",
      curationStatus: "reference",
      createdAt: august,
      updatedAt: september,
    },
  ],
  blocks: [
    {
      kind: "block",
      id: "block-thetis-drawing",
      type: "drawing",
      title: "Sail rig, first drawing",
      description: "Pencil study of mast, stays and the centre of the sail.",
      creatorId: "atlas",
      nodeId: "forum-plett",
      visibility: "node",
      curationStatus: "selected",
      payload: { visual: "boat", label: "drawing 01" },
      createdAt: july,
      updatedAt: july,
    },
    {
      kind: "block",
      id: "block-thetis-question",
      type: "question",
      title: "Can we make it sail?",
      creatorId: "atlas",
      nodeId: "forum-plett",
      visibility: "node",
      curationStatus: "none",
      payload: { body: "Can we make it sail without cutting the boat?" },
      createdAt: july,
      updatedAt: july,
    },
    {
      kind: "block",
      id: "block-thetis-observation",
      type: "observation",
      title: "Weight moved aft",
      creatorId: "atlas",
      nodeId: "forum-plett",
      visibility: "node",
      curationStatus: "none",
      payload: { body: "The front went higher when I sat at the back." },
      createdAt: september,
      updatedAt: september,
    },
    {
      kind: "block",
      id: "block-hull-length",
      type: "measurement",
      title: "Hull length",
      creatorId: "morgan",
      nodeId: "forum-plett",
      visibility: "node",
      curationStatus: "none",
      payload: { value: "2.48", unit: "m", body: "Measured along the centre line." },
      createdAt: july,
      updatedAt: july,
    },
    {
      kind: "block",
      id: "block-mast-test",
      type: "experiment",
      title: "Three mast positions",
      creatorId: "morgan",
      nodeId: "forum-plett",
      visibility: "node",
      curationStatus: "none",
      payload: { body: "Test the mast at 42, 58 and 74 cm from the bow. Record turning and heel." },
      createdAt: august,
      updatedAt: august,
    },
    {
      kind: "block",
      id: "block-wind-sensor",
      type: "component",
      title: "Pocket wind sensor",
      description: "A reusable anemometer component for boats, kites and weather Builds.",
      creatorId: "morgan",
      nodeId: "forum-plett",
      visibility: "network",
      curationStatus: "reference",
      payload: { body: "Hall sensor · printed cups · ESP32 logger" },
      createdAt: august,
      updatedAt: september,
    },
    {
      kind: "block",
      id: "block-submarine-drawing",
      type: "drawing",
      title: "Player submarine",
      creatorId: "atlas",
      nodeId: "forum-plett",
      visibility: "private",
      curationStatus: "none",
      payload: { visual: "sea", label: "sprite study" },
      createdAt: august,
      updatedAt: august,
    },
    {
      kind: "block",
      id: "block-shark-bug",
      type: "observation",
      title: "The shark overshoots",
      creatorId: "atlas",
      nodeId: "forum-plett",
      visibility: "private",
      curationStatus: "none",
      payload: { body: "When the submarine turns, the shark passes it and shakes left and right." },
      createdAt: september,
      updatedAt: september,
    },
    {
      kind: "block",
      id: "block-deep-sea-code",
      type: "code",
      title: "Follow behaviour",
      creatorId: "atlas",
      nodeId: "forum-plett",
      visibility: "private",
      curationStatus: "none",
      payload: {
        language: "gdscript",
        body: "velocity = velocity.lerp(direction * speed, 0.08)\nposition += velocity * delta",
      },
      createdAt: september,
      updatedAt: september,
    },
    {
      kind: "block",
      id: "block-deep-sea-repo",
      type: "repository",
      title: "Deep Sea repository",
      creatorId: "atlas",
      nodeId: "forum-plett",
      visibility: "private",
      curationStatus: "none",
      payload: { label: "Git repository · main", body: "Private repository connection planned." },
      createdAt: august,
      updatedAt: september,
    },
    {
      kind: "block",
      id: "block-rover-drawing",
      type: "image",
      title: "Rover in bed three",
      creatorId: "ines",
      nodeId: "forum-plett",
      visibility: "network",
      curationStatus: "reference",
      payload: { visual: "rover", label: "field photograph · 07:42" },
      createdAt: august,
      updatedAt: august,
    },
    {
      kind: "block",
      id: "block-rover-test",
      type: "experiment",
      title: "Edge test 04",
      creatorId: "ines",
      nodeId: "forum-plett",
      visibility: "network",
      curationStatus: "none",
      payload: { body: "Approach the timber edge at three angles. Stop distance must remain above 8 cm." },
      createdAt: september,
      updatedAt: september,
    },
    {
      kind: "block",
      id: "block-rover-result",
      type: "measurement",
      title: "Stop distance",
      creatorId: "atlas",
      nodeId: "forum-plett",
      visibility: "network",
      curationStatus: "none",
      payload: { value: "11.6", unit: "cm", body: "Median of nine approaches." },
      createdAt: september,
      updatedAt: september,
    },
  ],
  collections: [
    {
      kind: "collection",
      id: "collection-water-lines",
      slug: "water-lines",
      title: "Water / Lines",
      description: "Working references for things that float, turn, drift and measure water.",
      creatorId: "morgan",
      nodeId: "forum-plett",
      visibility: "node",
      curationStatus: "selected",
      createdAt: august,
      updatedAt: september,
    },
    {
      kind: "collection",
      id: "collection-responsive-machines",
      slug: "responsive-machines",
      title: "Responsive Machines",
      description: "Small machines that notice something and change what they do.",
      creatorId: "ines",
      nodeId: "forum-plett",
      visibility: "network",
      curationStatus: "reference",
      createdAt: august,
      updatedAt: september,
    },
  ],
  connections: [
    ...[
      "block-thetis-drawing",
      "block-thetis-question",
      "block-thetis-observation",
      "block-hull-length",
      "block-mast-test",
      "block-wind-sensor",
    ].map((id, position) => ({
      id: `connection-thetis-${position}`,
      source: { type: "build" as const, id: "build-thetis" },
      target: { type: "block" as const, id },
      relationship: "contains" as const,
      position,
      createdBy: "morgan",
      createdAt: september,
    })),
    ...[
      "block-submarine-drawing",
      "block-shark-bug",
      "block-deep-sea-code",
      "block-deep-sea-repo",
    ].map((id, position) => ({
      id: `connection-deep-sea-${position}`,
      source: { type: "build" as const, id: "build-deep-sea" },
      target: { type: "block" as const, id },
      relationship: "contains" as const,
      position,
      createdBy: "atlas",
      createdAt: september,
    })),
    ...[
      "block-rover-drawing",
      "block-rover-test",
      "block-rover-result",
      "block-wind-sensor",
    ].map((id, position) => ({
      id: `connection-rover-${position}`,
      source: { type: "build" as const, id: "build-garden-rover" },
      target: { type: "block" as const, id },
      relationship: "contains" as const,
      position,
      createdBy: "ines",
      createdAt: september,
    })),
    {
      id: "connection-water-thetis",
      source: { type: "collection", id: "collection-water-lines" },
      target: { type: "build", id: "build-thetis" },
      relationship: "contains",
      position: 0,
      createdBy: "morgan",
      createdAt: september,
    },
    {
      id: "connection-water-sensor",
      source: { type: "collection", id: "collection-water-lines" },
      target: { type: "block", id: "block-wind-sensor" },
      relationship: "contains",
      position: 1,
      createdBy: "morgan",
      createdAt: september,
    },
    {
      id: "connection-machines-rover",
      source: { type: "collection", id: "collection-responsive-machines" },
      target: { type: "build", id: "build-garden-rover" },
      relationship: "contains",
      position: 0,
      createdBy: "ines",
      createdAt: september,
    },
    {
      id: "connection-machines-sensor",
      source: { type: "collection", id: "collection-responsive-machines" },
      target: { type: "block", id: "block-wind-sensor" },
      relationship: "contains",
      position: 1,
      createdBy: "ines",
      createdAt: september,
    },
    {
      id: "connection-observation-tests-experiment",
      source: { type: "block", id: "block-thetis-observation" },
      target: { type: "block", id: "block-mast-test" },
      relationship: "tests",
      createdBy: "morgan",
      createdAt: september,
    },
  ],
  revisions: [
    {
      id: "revision-thetis-1",
      object: { type: "build", id: "build-thetis" },
      revisionNumber: 1,
      snapshot: { title: "Thetis", state: "exploring" },
      createdBy: "atlas",
      message: "Can we make it sail?",
      createdAt: july,
    },
    {
      id: "revision-thetis-2",
      object: { type: "build", id: "build-thetis" },
      revisionNumber: 2,
      snapshot: { title: "Thetis", state: "testing" },
      createdBy: "morgan",
      message: "Added the mast-position test.",
      createdAt: september,
    },
  ],
  guardianLinks: [{ guardianId: "morgan", childId: "atlas" }],
  nodeMemberships: [
    { nodeId: "forum-plett", userId: "atlas", role: "member" },
    { nodeId: "forum-plett", userId: "morgan", role: "admin" },
    { nodeId: "forum-plett", userId: "ines", role: "curator" },
  ],
  buildCollaborators: [
    { buildId: "build-thetis", userId: "morgan", role: "owner" },
    { buildId: "build-garden-rover", userId: "atlas", role: "contributor" },
  ],
  forumMemberships: [
    { userId: "atlas", role: "member" },
    { userId: "morgan", role: "admin" },
    { userId: "ines", role: "curator" },
  ],
};
